# Personal info
name: Megha Tiku
title: Backend Developer
email: megha.tiku@gmail.com
website: www.meghatiku.github.io
# Social links
# Social links
github_username:  meghatiku
linkedin_username: meghatiku

# About Section
# about_title: About Me
about_profile_image: images/megha.jpeg

about_content: |
  Hi! My name is Megha and I'm currently working as a backend developer at Shuttl.🚌
  Besides making *scalable* software and web applications, I like fixing bugs 🐞 and solving consumer problems.
  I love working in a team be it remote or onsite or as an individual contributer.
  I love data 📈 📊 visualizations `D3.js` 💙 and my target for 2020 is to learn a new language 📆

# More Section
# more_title: A Little More About Me
more_content: |
  Alongside my interests in software engineering and reading fiction some of my other hobbies are:
   - Solving Crosswords
   - 🔪 Experimenting with food
   - Kpop 💖 *Saranghe Oppa*
   - Calligraphy

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme


plugins:
 - jekyll-seo-tag
